### ISSUE TITLE
Custom circle radius / arrow lenght

### ISSUE THREAD

**Issue by sebaplaza** [coyotesqrl/Leaflet.ArrowCircle#1]
Hello,

There is any way to change the circle radius and the arrow length ?

It is possible to add this option ?

Thanks !

**Comment by coyotesqrl** [comment]
@sebaplaza I'm not sure at the moment, but I will take a look and see.

**Comment by coyotesqrl** [comment]
@sebaplaza The `size` option scales the circle and arrow up or down in size, but there is currently no option to change the length of the arrow separate from that.

If you take a look at the [demo in this repository](https://github.com/coyotesqrl/Leaflet.ArrowCircle/blob/master/examples/demo.html), you can see how the `size` option is used, and can play with that to see if it meets your needs.

If you need granular control of the length of the arrow separate from the scaling of the whole circle+arrow, I'm not sure how I feel about that change.

**Comment by coyotesqrl** [comment]
Sizing as a unit is already available; separate arrow and circle sizing is not something I want to provide.
